- name: Reload systemd
  ansible.builtin.systemd:
    daemon_reload: true
  become: true

- name: Restart robodogmonitor
  ansible.builtin.systemd:
    name: robodogmonitor.service
    state: restarted
  become: true

